### ISSUE TITLE
03 - HTML:  (All) Create header (logo & title and nav bar)

### ISSUE THREAD

**Issue by bgarnaat** [bgarnaat/starving_artists#3]
Create a header in HTML to hold logo & title / slogan 
Create a nav bar below logo & title/slogan
header will be used in all html pages.

**Comment by bgarnaat** [comment]
Include nav bar in header (issue 04)

**Comment by sgruse** [comment]
Starting on the navbar and title location

**Comment by sgruse** [comment]
Also added a footer.
