### ISSUE TITLE
33 - JS:  (HTML Generator) Create function to generate search results cards

### ISSUE THREAD

**Issue by bgarnaat** [bgarnaat/starving_artists#33]
Create a function to generate cards to display search results.

Each card will include:
(in div/article)
- show name
- show time
- show dates (start & end)
- show venue
  (<p> next to div/article)
- show description
  (img next to <p>)
- picture for show
  (venue details:  below, expand on click venue)
  (in div/article)
- venue name
- venue address
- venue neighborhood
- venue box office hours
- venue phone
- venue occupancy
  (<p> next to div/article)
- venue description

**Comment by bgarnaat** [comment]
Behold the power of this fully functional search box.\*  
- NOW WITH 200% MORE VENUE CARD EVENT HANDLER! \o/
  Completed:  2016/01/26

**Comment by simonszc** [comment]
LIKE.
